/**
 * tui-v2 testkit conformance corpus (WP-02, plan §9.2/WP-02).
 *
 * Fixtures live in fixtures/tui-v2/conformance/*.jsonl, one case per file:
 *   line 1:  { kind:'header', conformanceVersion:1, name, profile,
 *              oracle:'xterm-cross-check'|'conservative-only', seed }
 *   then:    { kind:'write', data }        (JSON-escaped terminal bytes)
 *            { kind:'resize', width, height }
 *            { kind:'expectUnsupported', count }
 *   last:    { kind:'expectedGrid', value: GoldenGrid }
 *
 * Oracle semantics:
 *   - 'xterm-cross-check': expectedGrid is REQUIRED and holds the projected
 *     pinned-xterm snapshot (readable). Evaluation replays BOTH parsers and
 *     asserts projectToXtermComparable(vt) == projected xterm == expectedGrid
 *     (compareGrid is the only assertion entry). Only the mutually
 *     expressible surface is compared — see xterm-oracle.ts for the boundary.
 *   - 'conservative-only': two shapes. Unknown/unsupported sequence cases
 *     carry NO expectedGrid and MUST carry expectUnsupported — evaluation
 *     asserts the exact unsupportedCount and that the grid is byte-identical
 *     to replaying only the resize lines (i.e. unpolluted). Cases the xterm
 *     oracle fundamentally cannot express (grapheme clustering, ambiguous
 *     wide, image placements) MAY carry a human-reviewed expectedGrid
 *     generated by the local VT (plan §9.2 allows human-reviewed cell
 *     fixtures); evaluation asserts with a full compareGrid.
 *
 * Golden files (test/tui-v2/goldens/*.json) are the §9.2 second class —
 * independent semantic oracles for the five required scenarios. Shape:
 *   { name, profile, input: GoldenStep[], expected: GoldenGrid(readable) }
 * where GoldenStep = { kind:'write', data } | { kind:'resize', width, height }.
 * (`input` is a step list rather than one byte string because a resize
 * scenario cannot be expressed in the byte stream itself; a plain string is
 * accepted and treated as a single write step.)
 */
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { TerminalProfile } from '../terminal/profile.js'
import {
  compareGrid,
  gridSha256,
  validateGoldenGrid,
  type GoldenGrid,
  type GridComparison,
  type GridDiff,
} from './canonical.js'
import { findLineWidthViolations } from './frame-assert.js'
import { PROFILES, getProfile } from './terminal-profiles.js'
import { VirtualTerminal } from './virtual-terminal.js'
import { XtermOracle, projectToXtermComparable } from './xterm-oracle.js'

export const CONFORMANCE_VERSION = 1

/** The five independent golden scenarios required by plan §9.2/WP-02. */
export const REQUIRED_GOLDENS = ['first-frame', 'resize', 'scrollback', 'overlay', 'cleanup'] as const

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

export type ConformanceOracle = 'xterm-cross-check' | 'conservative-only'

export interface ConformanceHeader {
  readonly kind: 'header'
  readonly conformanceVersion: 1
  readonly name: string
  readonly profile: string
  readonly oracle: ConformanceOracle
  readonly seed: number
}
export interface ConformanceWriteLine {
  readonly kind: 'write'
  readonly data: string
}
export interface ConformanceResizeLine {
  readonly kind: 'resize'
  readonly width: number
  readonly height: number
}
export interface ConformanceExpectUnsupportedLine {
  readonly kind: 'expectUnsupported'
  readonly count: number
}
export interface ConformanceExpectedGridLine {
  readonly kind: 'expectedGrid'
  readonly value: GoldenGrid
}
export type ConformanceOpLine = ConformanceWriteLine | ConformanceResizeLine
export type ConformanceBodyLine =
  | ConformanceOpLine
  | ConformanceExpectUnsupportedLine
  | ConformanceExpectedGridLine

export interface ConformanceCase {
  readonly header: ConformanceHeader
  readonly lines: readonly ConformanceBodyLine[]
}

export interface ConformanceValidation {
  readonly ok: boolean
  readonly errors: readonly string[]
  readonly warnings: readonly string[]
}

function fail(message: string): never {
  throw new TypeError(`invalid conformance case: ${message}`)
}

function validateHeader(value: unknown): ConformanceHeader {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) fail('header must be an object')
  const h = value as Record<string, unknown>
  if (h.kind !== 'header') fail("first line kind must be 'header'")
  if (h.conformanceVersion !== CONFORMANCE_VERSION) fail(`conformanceVersion must be ${CONFORMANCE_VERSION}`)
  if (typeof h.name !== 'string' || h.name === '') fail('name must be a non-empty string')
  if (typeof h.profile !== 'string' || !PROFILES.has(h.profile)) {
    fail(`profile must be a known profile id, got ${JSON.stringify(h.profile)}`)
  }
  if (h.oracle !== 'xterm-cross-check' && h.oracle !== 'conservative-only') {
    fail("oracle must be 'xterm-cross-check'|'conservative-only'")
  }
  if (!Number.isInteger(h.seed)) fail('seed must be an integer (fixtures must declare a seed)')
  return h as unknown as ConformanceHeader
}

function validateBodyLine(value: unknown): ConformanceBodyLine {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) fail('line must be an object')
  const line = value as Record<string, unknown>
  switch (line.kind) {
    case 'write':
      if (typeof line.data !== 'string') fail('write.data must be a string')
      return line as unknown as ConformanceWriteLine
    case 'resize':
      if (!Number.isInteger(line.width) || !Number.isInteger(line.height)) fail('resize width/height must be integers')
      if ((line.width as number) < 1 || (line.height as number) < 1) fail('resize width/height must be >= 1')
      if ((line.width as number) > 512 || (line.height as number) > 512) fail('resize width/height must be <= 512')
      return line as unknown as ConformanceResizeLine
    case 'expectUnsupported':
      if (!Number.isInteger(line.count) || (line.count as number) < 0) fail('expectUnsupported.count must be a non-negative integer')
      return line as unknown as ConformanceExpectUnsupportedLine
    case 'expectedGrid':
      validateGoldenGrid(line.value)
      return line as unknown as ConformanceExpectedGridLine
    default:
      fail(`unknown line kind ${String(line.kind)}`)
  }
}

/** Structural + semantic validation of a parsed conformance case. */
export function validateConformance(kase: ConformanceCase): ConformanceValidation {
  const errors: string[] = []
  const warnings: string[] = []
  try {
    validateHeader(kase.header)
  } catch (error) {
    errors.push(String((error as Error)?.message ?? error))
    return { ok: false, errors, warnings }
  }
  let sawExpectedGrid = false
  let sawExpectUnsupported = false
  for (const [i, line] of kase.lines.entries()) {
    try {
      validateBodyLine(line)
    } catch (error) {
      errors.push(`line ${i + 2}: ${String((error as Error)?.message ?? error)}`)
      continue
    }
    if (line.kind === 'expectedGrid') {
      if (sawExpectedGrid) errors.push(`line ${i + 2}: duplicate expectedGrid`)
      if (i !== kase.lines.length - 1) errors.push(`line ${i + 2}: expectedGrid must be the last line`)
      sawExpectedGrid = true
    }
    if (line.kind === 'expectUnsupported') sawExpectUnsupported = true
  }
  if (kase.header.oracle === 'xterm-cross-check' && !sawExpectedGrid) {
    errors.push("oracle 'xterm-cross-check' requires an expectedGrid line")
  }
  if (kase.header.oracle === 'conservative-only' && !sawExpectedGrid && !sawExpectUnsupported) {
    errors.push("oracle 'conservative-only' without expectedGrid requires expectUnsupported")
  }
  if (kase.header.oracle === 'conservative-only' && sawExpectedGrid) {
    warnings.push('conservative-only expectedGrid is locally generated and must be human-reviewed (§9.2)')
  }
  return { ok: errors.length === 0, errors, warnings }
}

/** Parse and validate a conformance fixture file (JSONL, one case per file). */
export async function readConformance(filePath: string): Promise<ConformanceCase> {
  const raw = await readFile(filePath, 'utf8')
  const physicalLines = raw.split('\n')
  if (physicalLines.length > 0 && physicalLines[physicalLines.length - 1] === '') physicalLines.pop()
  if (physicalLines.length === 0) fail(`${filePath} is empty`)

  const parseLine = (lineNo: number): Record<string, unknown> => {
    let parsed: unknown
    try {
      parsed = JSON.parse(physicalLines[lineNo - 1])
    } catch (error) {
      fail(`${filePath}:${lineNo}: invalid JSON: ${String((error as Error)?.message ?? error)}`)
    }
    if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
      fail(`${filePath}:${lineNo}: line must be a JSON object`)
    }
    return parsed as Record<string, unknown>
  }

  let header: ConformanceHeader
  try {
    header = validateHeader(parseLine(1))
  } catch (error) {
    fail(`${filePath}:1: ${String((error as Error)?.message ?? error)}`)
  }
  const lines: ConformanceBodyLine[] = []
  for (let lineNo = 2; lineNo <= physicalLines.length; lineNo++) {
    try {
      lines.push(validateBodyLine(parseLine(lineNo)))
    } catch (error) {
      fail(`${filePath}:${lineNo}: ${String((error as Error)?.message ?? error)}`)
    }
  }
  const kase: ConformanceCase = { header, lines }
  const result = validateConformance(kase)
  if (!result.ok) fail(`${filePath}: ${result.errors.join('; ')}`)
  return kase
}

/** Validate then persist a conformance case as JSONL (atomic). */
export async function writeConformance(filePath: string, kase: ConformanceCase): Promise<void> {
  const result = validateConformance(kase)
  if (!result.ok) fail(`refusing to write ${filePath}: ${result.errors.join('; ')}`)
  const lines = [JSON.stringify(kase.header)]
  for (const line of kase.lines) lines.push(JSON.stringify(line))
  await mkdir(path.dirname(filePath), { recursive: true })
  const tmp = path.join(
    path.dirname(filePath),
    `.${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`,
  )
  await writeFile(tmp, `${lines.join('\n')}\n`, 'utf8')
  await rename(tmp, filePath)
}

// ---------------------------------------------------------------------------
// Golden file schema (test/tui-v2/goldens/*.json)
// ---------------------------------------------------------------------------

export type GoldenStep = ConformanceOpLine

export interface GoldenFile {
  readonly name: string
  readonly profile: string
  /** Replay steps; a plain string is shorthand for one write step. */
  readonly input: string | readonly GoldenStep[]
  readonly expected: GoldenGrid
}

export function validateGoldenFile(value: unknown): GoldenFile {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new TypeError('invalid golden file: must be an object')
  }
  const g = value as Record<string, unknown>
  if (typeof g.name !== 'string' || g.name === '') throw new TypeError('invalid golden file: name must be a non-empty string')
  if (typeof g.profile !== 'string' || !PROFILES.has(g.profile)) {
    throw new TypeError(`invalid golden file: unknown profile ${JSON.stringify(g.profile)}`)
  }
  const steps = normalizeGoldenSteps(g.input as GoldenFile['input'])
  for (const step of steps) {
    if (step.kind !== 'write' && step.kind !== 'resize') {
      throw new TypeError(`invalid golden file: input steps must be write|resize, got ${String((step as { kind: unknown }).kind)}`)
    }
    validateBodyLine(step)
  }
  const expected = validateGoldenGrid(g.expected)
  if (expected.gridEncoding !== 'readable') {
    throw new TypeError('invalid golden file: expected must use gridEncoding readable (§9.2 review requirement)')
  }
  return g as unknown as GoldenFile
}

export function normalizeGoldenSteps(input: GoldenFile['input']): GoldenStep[] {
  if (typeof input === 'string') return [{ kind: 'write', data: input }]
  if (!Array.isArray(input)) throw new TypeError('invalid golden file: input must be a string or an array of steps')
  return input as GoldenStep[]
}

export async function readGoldenFile(filePath: string): Promise<GoldenFile> {
  let parsed: unknown
  try {
    parsed = JSON.parse(await readFile(filePath, 'utf8'))
  } catch (error) {
    throw new TypeError(`${filePath}: invalid JSON: ${String((error as Error)?.message ?? error)}`)
  }
  try {
    return validateGoldenFile(parsed)
  } catch (error) {
    throw new TypeError(`${filePath}: ${String((error as Error)?.message ?? error)}`)
  }
}

// ---------------------------------------------------------------------------
// Replay helpers
// ---------------------------------------------------------------------------

export function replayVirtualTerminal(profile: TerminalProfile, ops: readonly GoldenStep[]): VirtualTerminal {
  const vt = new VirtualTerminal(profile)
  for (const op of ops) {
    if (op.kind === 'write') vt.write(op.data)
    else vt.resize(op.width, op.height)
  }
  return vt
}

export async function replayXtermOracle(profile: TerminalProfile, ops: readonly GoldenStep[]): Promise<XtermOracle> {
  const oracle = new XtermOracle(profile)
  for (const op of ops) {
    if (op.kind === 'write') await oracle.write(op.data)
    else oracle.resize(op.width, op.height)
  }
  return oracle
}

// ---------------------------------------------------------------------------
// Case evaluation (shared by tests and `verify --check trace`)
// ---------------------------------------------------------------------------

export interface ConformanceEvaluation {
  readonly name: string
  readonly profile: string
  readonly oracle: ConformanceOracle
  readonly seed: number
  readonly ok: boolean
  readonly errors: readonly string[]
  readonly unsupportedCount: number
  readonly vtHash: string
  /** Present for xterm-cross-check cases. */
  readonly xtermHash?: string
  /** Sanitized diffs from the FIRST failing comparison. */
  readonly diffs?: readonly GridDiff[]
  readonly lineWidthViolations: readonly string[]
}

function asGoldenReadable(grid: Parameters<typeof compareGrid>[0]): GoldenGrid {
  return { gridEncoding: 'readable', value: grid }
}

function firstDiffs(...comparisons: GridComparison[]): readonly GridDiff[] | undefined {
  for (const comparison of comparisons) {
    if (!comparison.ok) return comparison.diffs
  }
  return undefined
}

/** Replay one case through the required parser(s) and evaluate it. */
export async function evaluateConformanceCase(kase: ConformanceCase): Promise<ConformanceEvaluation> {
  const errors: string[] = []
  const profile = getProfile(kase.header.profile)
  const ops = kase.lines.filter((line): line is ConformanceOpLine => line.kind === 'write' || line.kind === 'resize')
  const expectedUnsupported = kase.lines.find((line) => line.kind === 'expectUnsupported')
  const expectedGrid = kase.lines.find((line) => line.kind === 'expectedGrid')

  const vt = replayVirtualTerminal(profile, ops)
  const vtSnapshot = vt.snapshot()
  const diagnostics = vt.diagnostics()
  const lineWidthViolations = findLineWidthViolations(vtSnapshot)
  for (const violation of lineWidthViolations) errors.push(`line-width invariant: ${violation}`)

  if (expectedUnsupported !== undefined && diagnostics.unsupportedCount !== expectedUnsupported.count) {
    errors.push(`unsupportedCount ${diagnostics.unsupportedCount} !== expectUnsupported ${expectedUnsupported.count}`)
  }

  let vtHash = gridSha256(vtSnapshot)
  let xtermHash: string | undefined
  let diffs: readonly GridDiff[] | undefined

  if (kase.header.oracle === 'xterm-cross-check') {
    const oracle = await replayXtermOracle(profile, ops)
    try {
      const xtermSnapshot = oracle.snapshot()
      const projectedVt = projectToXtermComparable(vtSnapshot)
      const projectedXterm = projectToXtermComparable(xtermSnapshot)
      vtHash = gridSha256(projectedVt)
      xtermHash = gridSha256(projectedXterm)
      // Live cross-check: both parsers must agree on the same byte stream.
      const live = compareGrid(projectedVt, asGoldenReadable(projectedXterm))
      if (!live.ok) errors.push('virtual terminal disagrees with xterm oracle (live cross-check)')
      // Drift guard: the stored xterm-generated golden must still match.
      if (expectedGrid !== undefined) {
        const stored = compareGrid(projectedVt, expectedGrid.value)
        if (!stored.ok) errors.push('virtual terminal disagrees with stored expectedGrid')
        diffs = firstDiffs(live, stored)
      } else {
        diffs = firstDiffs(live)
      }
    } finally {
      oracle.dispose()
    }
  } else if (expectedGrid !== undefined) {
    // conservative-only with a human-reviewed local golden: full compareGrid.
    const stored = compareGrid(vtSnapshot, expectedGrid.value)
    if (!stored.ok) errors.push('virtual terminal disagrees with stored expectedGrid')
    diffs = firstDiffs(stored)
  } else {
    // conservative-only unknown-sequence case: the grid must be identical to
    // replaying only the resize lines (no pollution), byte for byte.
    const baselineOps = ops.filter((op) => op.kind === 'resize')
    const baseline = replayVirtualTerminal(profile, baselineOps).snapshot()
    const pristine = compareGrid(vtSnapshot, asGoldenReadable(baseline))
    if (!pristine.ok) errors.push('grid polluted by unsupported sequences')
    diffs = firstDiffs(pristine)
  }

  return {
    name: kase.header.name,
    profile: kase.header.profile,
    oracle: kase.header.oracle,
    seed: kase.header.seed,
    ok: errors.length === 0,
    errors,
    unsupportedCount: diagnostics.unsupportedCount,
    vtHash,
    ...(xtermHash !== undefined ? { xtermHash } : {}),
    ...(diffs !== undefined ? { diffs } : {}),
    lineWidthViolations,
  }
}

/** Replay a golden file from a clean VirtualTerminal state and compare. */
export function evaluateGoldenFile(golden: GoldenFile): {
  readonly ok: boolean
  readonly errors: readonly string[]
  readonly diffs?: readonly GridDiff[]
  readonly gridHash: string
  readonly lineWidthViolations: readonly string[]
} {
  const errors: string[] = []
  const profile = getProfile(golden.profile)
  const vt = replayVirtualTerminal(profile, normalizeGoldenSteps(golden.input))
  const snapshot = vt.snapshot()
  const lineWidthViolations = findLineWidthViolations(snapshot)
  for (const violation of lineWidthViolations) errors.push(`line-width invariant: ${violation}`)
  const comparison = compareGrid(snapshot, golden.expected)
  if (!comparison.ok) errors.push('golden mismatch')
  return {
    ok: errors.length === 0,
    errors,
    ...(comparison.ok ? {} : { diffs: comparison.diffs }),
    gridHash: gridSha256(snapshot),
    lineWidthViolations,
  }
}

/**
 * Fixture integrity guard (WP-02 gate: any control-sequence injection fails):
 * terminal write payloads obviously contain ESC bytes by design; what must
 * never appear are C0/C1 control bytes inside EXPECTED GRID graphemes (that
 * would mean a fixture smuggled control sequences into golden cell data).
 */
export function findGridControlInjection(grid: { readonly cells: readonly { grapheme: string }[]; readonly scrollback: readonly (readonly { grapheme: string }[])[] }): string[] {
  const violations: string[] = []
  const scan = (grapheme: string, label: string) => {
    for (const ch of grapheme) {
      const cp = ch.codePointAt(0) as number
      if (cp < 0x20 || cp === 0x7f || (cp >= 0x80 && cp <= 0x9f)) {
        violations.push(`${label}: control char 0x${cp.toString(16)} in grapheme`)
        return
      }
    }
  }
  grid.cells.forEach((cell, i) => scan(cell.grapheme, `cells[${i}]`))
  grid.scrollback.forEach((line, i) => line.forEach((cell, j) => scan(cell.grapheme, `scrollback[${i}][${j}]`)))
  return violations
}
